{% set name = "pvaPy" %}
{% set version = "2.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/epics-base/{{ name }}/archive/{{ version }}.tar.gz
  sha256: ae86a9184c33f1bb06703a6ebf20c8202f34c061624eae29657ec849f07c3d82

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - make
    - autoconf
    - automake
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - epics-base >=7
    - readline
    - python
    - boost
    - numpy
  run:
    - python
    - boost
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - pvaccess

about:
  home: https://github.com/epics-base/pvaPy
  license: EPICS Open License
  license_file: LICENSE
  summary: Python library for EPICS PV Access
  description: |
    The PvaPy package is a Python API for EPICS4. It supports both PVA and CA providers,
    all standard EPICS4 types (structures, scalars, unions, etc), standard set of channel
    operations (put/get, monitor), RPC client/server, PVA server, etc. It uses Boost/Python
    to wrap EPICS4 C++ libraries and APIs, and is currently supported on the
    Unix-like operating systems (Linux, OSX).
  doc_url: https://epics.anl.gov/extensions/pvaPy/production/index.html
  dev_url: https://github.com/epics-base/pvaPy

extra:
  recipe-maintainers:
    - beenje
