{% set name = "poco" %}
{% set version = "1.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/pocoproject/poco/archive/poco-{{ version }}-release.tar.gz
  sha256: 45ec5c759d2ad02bb812745f6cb585aa04af025c921b1bb4bdefa108ce4f1756

build:
  number: 0
  skip: true    # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake >=3.0
  host:
    - openssl

test:
  commands:
    - cpspc -h
    - f2cpsp -h

about:
  home: https://github.com/pocoproject/poco
  license: BSL-1.0
  license_file: LICENSE
  summary: POrtable COmponents C++ Libraries
  description: |
    The POCO C++ Libraries are powerful cross-platform C++ libraries
    for building network- and internet-based applications that run
    on desktop, server, mobile, IoT, and embedded systems.
  doc_url: https://pocoproject.org
  dev_url: https://github.com/pocoproject/poco

extra:
  recipe-maintainers:
    - beenje
