{% set name = "tango-admin" %}
{% set version = "1.15" %}
{% set sha256 = "55f6f358fdd20cbace606633ee1ed3a6676323a4898de0acc842c8f941d77533" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/tango-controls/tango_admin/archive/Release_{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - tango_admin-install.patch

build:
  number: 0
  skip: true  # [not linux]

requirements:
  build:
    - cmake
    - make
    - {{ compiler('cxx') }}
    - libtool
    - pkg-config
  host:
    - cppzmq
    - cpptango
  run:
    # cpptango set in run_exports
    - {{ pin_compatible('omniorb', min_pin='x.x', max_pin='x.x') }}

test:
  commands:
    - tango_admin --help

about:
  home: https://www.tango-controls.org
  license: GPL-3.0-only
  license_file: LICENSE
  summary: 'Tango database command line interface'
  description: |
   Tango-Controls is a software toolkit for building control systems.
   This utility is a Tango database command line interface.
   Obviously, not all the database features are interfaced by this tool.
  dev_url: https://github.com/tango-controls/tango_admin

extra:
  recipe-maintainers:
    - beenje
    - bourtemb
